[package]
name = "rust-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = {version = "1", features = ["derive"]}
serde_json = "1.0.137"
uuid = {version = "1", features = ["v4"]}
dotenv = "0.15.0"
tokio = {version = "1", features = ["full"]}
